#!/usr/bin/env bash
# sweep.sh — Orchestrate all experiments for AI-Augmented Financial Anomaly Detection
# AUTO-GENERATED by gen_sweep.py from project.yaml
# Re-run generator after changing project.yaml experiment matrix.
set -euo pipefail

SEEDS="42,123,456"
PARTS="all"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    echo "Usage: bash $0 [--parts {1,2,3,4,all}] [--seeds SEED_LIST]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parts) PARTS="$2"; shift 2 ;;
        --seeds) SEEDS="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; usage ;;
    esac
done

IFS=',' read -ra SEED_ARRAY <<< "$SEEDS"
cd "$PROJECT_DIR"
export PYTHONHASHSEED=0

run_part1() {
    echo "=== Part 1: baselines ==="
    for method in logistic_regression random_forest xgboost; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/train_baselines.py \
                --sample-frac 1.0
        done
    done
}

run_part2() {
    echo "=== Part 2: anomaly_detection ==="
    for method in isolation_forest local_outlier_factor autoencoder; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/train_anomaly.py \
                --method $method --seed $seed
        done
    done
}

run_part3() {
    echo "=== Part 3: explainability ==="
    for method in shap feature_importance; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_explainability.py \
                --method $method --seed $seed
        done
    done
}

run_part4() {
    echo "=== Part 4: adversarial_eval ==="
    for method in feature_controllability; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/adversarial_eval.py \
                --method $method --seed $seed
        done
    done
}

case "$PARTS" in
    1) run_part1 ;;
    2) run_part2 ;;
    3) run_part3 ;;
    4) run_part4 ;;
    all) run_part1; run_part2; run_part3; run_part4 ;;
    *) echo "Unknown part: $PARTS"; usage ;;
esac

echo ''
echo "=== Sweep complete ==="
